jobs:
  build:
    working_directory: ~/circleci-demo-java-spring
    steps:
      - run: 
        command: 'echo "test yml"'
test:
  override:
    - java -version 
    - echo CIRCLE_BRANCH

machine:
  environment:
    DATABASE_URL: http://localhost:800/phpmyadmin/#PMAURL-1:db_structure.php?db=garderie&table=&server=1&target=&token=95bb5c94ac575adf3077ac1072440729

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - test1
      - deploy:
          requires:
            - test2


