jobs:
  build:
    working_directory: ~/circleci-demo-java-spring
  docker:
      - image: ruby:2.3.1
        environment:
        - PG_HOST=localhost
        - PG_USER=ubuntu
        - RAILS_ENV=test
        - RACK_ENV=test
      # The following example uses the official postgres 9.6 image, you may also use circleci/postgres:9.6 
      # which includes a few enhancements and modifications. It is possible to use either image.
      - image: postgres:9.6
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=db_name
  steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run: 
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
        environment:
          DATABASE_URL: "postgres://ubuntu@localhost:5432/db_name"

test:
  override:
    - java -version 
    - echo CIRCLE_BRANCH

machine:
  environment:
    DATABASE_URL: http://localhost:800/phpmyadmin/#PMAURL-1:db_structure.php?db=garderie&table=&server=1&target=&token=95bb5c94ac575adf3077ac1072440729

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - test2:
          requires:
            - test1
      - deploy:
          requires:
            - test2

    
